repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: lint-and-format
        name: Lint and Format
        entry: bash -c "pdm run format && pdm run lint"
        language: system
        stages: [pre-push]
