# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    env_file:
      - ./local.env

  wordpress:
    image: docker.io/bitnami/wordpress:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
    depends_on:
      - mariadb
    env_file:
      - ./local.env

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
