services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    env_file:
      - ./local.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    cpus: 1.0

  wordpress:
    image: docker.io/bitnami/wordpress:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./local.env
    mem_limit: 2G
    cpus: 2.0

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
