[project]
name = "woocommerce-playwright-python"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Rodel Calasagsag", email = "od.rodel.calasagsag@gmail.com"},
]
dependencies = []
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "docker-compose up -d"
stop = "docker-compose down --volumes"
restart = {composite = ["stop", "start"]}

[dependency-groups]
test = [
    "pytest-playwright>=0.7.0",
]
