name: Daily Test Run
run-name: daily-test-run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
env:
  FORCE_COLOR: "1"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Start local site
        run: pdm start

      - name: Run tests
        run: pdm run test
